---
- name: Check vCenter Server
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Check vCenter Server status
      ansible.builtin.uri:
        url: "https://{{ vcenter_server }}/rest/com/vmware/cis/session"
        method: GET
        user: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
      register: result

    - name: Display vCenter Server status
      ansible.builtin.debug:
        msg: "vCenter Server status: {{ result.status }}"
