---
- hosts: all
  tasks:
  - name: Package installation
    dnf:
      name:
        - unzip
        - curl
      state: latest
  - name: OCP Install and Client Installation
    ansible.builtin.shell: |  
      mkdir ocp
      cd ocp/
      curl -O -k https://"{{ vcenterurl }}"/certs/download.zip
      unzip download.zip
      cp certs/lin/* /etc/pki/ca-trust/source/anchors
      update-ca-trust extract    
      curl "https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/stable-{{ ocp_version }}/openshift-install-linux.tar.gz" | tar xz -C /tmp
      mv /tmp/openshift-install /usr/local/bin 
      curl "https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/stable-{{ ocp_version }}/openshift-client-linux.tar.gz" | tar xz -C /tmp
      mv /tmp/oc /usr/local/bin 
      mv /tmp/kubectl /usr/local/bin 
