---
- name: Check DNS Records for OpenShift API and AppD
  hosts: all
  
  tasks:
    - name: Check OpenShift API DNS record
      ansible.builtin.shell: "dig +short {{ dns_api_openshift_cluster }}"
      register: openshift_api_result

    - name: Debug OpenShift API DNS record result
      ansible.builtin.debug:
        msg: "OpenShift API DNS record: {{ openshift_api_result.stdout }}"

    - name: Check AppD DNS record
      ansible.builtin.shell: "dig +short {{ dns_apps_openshift_cluster }}"
      register: appd_result

    - name: Debug AppD DNS record result
      ansible.builtin.debug:
        msg: "AppD DNS record: {{ appd_result.stdout }}"
