---
- hosts: all
  tasks:
  - name: Package installation
    dnf:
      name:
        - unzip
        - curl
      state: latest
  - name: OCP Preparation add vcenter certs to bastion 
    ansible.builtin.shell: | 
      warn: false
      mkdir "{{ ocp_install_folder }}"
      cd "{{ ocp_install_folder }}"/
      curl -O -k https://"{{ vcenterurl }}"/certs/download.zip
      unzip download.zip
      cp certs/lin/* /etc/pki/ca-trust/source/anchors
      update-ca-trust extract    
      register: ocp_preparation_certs
  - debug: msg="{{ocp_preparation.stdout}}"

  - name: OCP Preparation download openshift-install and oc client
    ansible.builtin.shell: |
      cd /root/"{{ ocp_install_folder }}"/
      curl -O -k "https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/{{ ocp_version }}/openshift-install-linux.tar.gz" 
      tar xvf openshift-install-linux.tar.gz -C /tmp
      mv /tmp/openshift-install /usr/local/bin 
      curl -O -k "https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/{{ ocp_version }}/openshift-client-linux.tar.gz"
      tar xvf openshift-client-linux.tar.gz -C /tmp
      mv /tmp/oc /usr/local/bin 
      mv /tmp/kubectl /usr/local/bin
      register: ocp_preparation_openshift_install_oc
  - debug: msg="{{ocp_preparation_openshift_install_oc.stdout}}"
      
      
