---
- name: Check DNS Records for OpenShift API and AppD
  hosts: localhost
  
  tasks:
    - name: Check OpenShift API DNS record
      ansible.builtin.shell: "dig +short {{ dns-api-openshift-cluster }}"
      register: openshift_api_result

    - name: Debug OpenShift API DNS record result
      ansible.builtin.debug:
        msg: "OpenShift API DNS record: {{ openshift_api_result.stdout_lines }}"

    - name: Check AppD DNS record
      ansible.builtin.shell: "dig +short {{ dns-apps-openshift-cluster }}"
      register: appd_result

    - name: Debug AppD DNS record result
      ansible.builtin.debug:
        msg: "AppD DNS record: {{ appd_result.stdout_lines }}"
